//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyDescription("ServiceA")]
[assembly: AssemblyCompany("Solutions")]
[assembly: AssemblyProduct("ServiceA")]
[assembly: AssemblyCopyright("Copyright (c) 2016")]

